[tool.poe.tasks.generate-ssl-certs]
shell = """
    mkdir -p src/bentochain/ssl
    cd src/bentochain/ssl
    openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -sha256 -days 365 -nodes
"""
help = "Generate self-signed SSL certificates for the web server"
