forticlient:
    name: null
    descriptions: null
    gateway: ENC[AES256_GCM,data:0LdxHmLTFCTduVM=,iv:h0tw/Vx7H6orHPLNIQh/anCNbrfG8aHZDfW3JwDyTME=,tag:J1Hytczuji1bVH+RlT9UZg==,type:str]
    port: ENC[AES256_GCM,data:hnSRwlM=,iv:INUCtWO8dz6dPh2/wmb6fyTd8OLVElROb8iWXjidvh4=,tag:4AGxNsbohIEqs2XjTEyrkg==,type:int]
users:
    chuai1: ENC[AES256_GCM,data:2dl9vCsmojJRaHQ=,iv:wAauOSdaX/qQUWRPDGVdttOjlUdqjO6sg/a08blxDng=,tag:Wl2D50YaEm3GhoYZSULP7g==,type:str]
    chuai2: ENC[AES256_GCM,data:uOJpHwPOESPsMWs=,iv:F0TenTphuvdi95kd1TpmI5Dw4W1sLNq47+KKj4qOFNc=,tag:dNlIRsGdqQWQdZjoorKvsQ==,type:str]
    chuai3: ENC[AES256_GCM,data:j5uzdHqchabGdBPH,iv:j3Vz1WEUlsaKnneOXJlStLMlO4DvwOjVu04XnGps5gE=,tag:5k4Aosm8eT+5uCToJ8DIMg==,type:str]
    chuai4: ENC[AES256_GCM,data:8+c+2v0qS67aDFY=,iv:9y1oxv4Id7hwwDdXsWsXk3sQvXH/yN2J89so9EOANKQ=,tag:LGTfi/jAUcakUZOOI2kISw==,type:str]
    chuai5: ENC[AES256_GCM,data:C4HgKjt/t2yE+yo=,iv:1emc7lXaw2/wzfvbPS8daMaUAg85lJe2/VZKetrWZ60=,tag:ampdPPmbsaDfN9USDlLMFw==,type:str]
    chuai6: ENC[AES256_GCM,data:UqaHVNd0h86IcGqQ,iv:TKw/M8cuMmkwB+RHA3XKw/ejLFjSc8+ucinthbKY/h4=,tag:aFSqFd+mkB0DFWGDa9REAg==,type:str]
    chuai7: ENC[AES256_GCM,data:A7gHAljlbT4MYrw=,iv:Uho3dLgG3kqGqIodinmWiBKE9PgSrr84K37OzIXcJXU=,tag:IsGd2MHZy8YVYEa1IqA5sg==,type:str]
    chuai8: ENC[AES256_GCM,data:nks71EZWr4F2yRU=,iv:HdSAC5G8LczAZdgRB7D1Z15QwASqnYtH7HjTxT1CoLQ=,tag:sP8u3B/89/l/KxJUKeB3Sg==,type:str]
servers:
    30.0.0.112: ENC[AES256_GCM,data:i+eJeU1CMbtL66YuFuE=,iv:sFpImeGsAQbxfEVvdCDmwnoG7QorpWH9rwjHeruQC4w=,tag:iemDU7LbMyn/9dnp7M7QHg==,type:str]
    30.0.0.37: ENC[AES256_GCM,data:/19d+CUrXtG9Wm0HQ/o=,iv:rw3tS9AbSjYwavkfEg0sKfh2TCUCNMftCsbOiTRgeaw=,tag:iojpb4Y09T1+s4cobfVYyw==,type:str]
    30.0.0.55: ENC[AES256_GCM,data:5ysXTnp6w7drzV993ps=,iv:CPL4SkHogBxZLos4E6l2fHUk/SbQ9tUMUXarjLbccOM=,tag:Uqkz/QcPsNR+7u2EzESp+g==,type:str]
    30.0.0.17: ENC[AES256_GCM,data:M0VcFT+E+ciqVYGa5vM=,iv:ESkwm6IC99Ds0CeNbECKZfReaxt/Y3ns5O5NHbFWWEs=,tag:WvrI1IdqFBGoCzMuQWEmrQ==,type:str]
    30.0.0.194: ENC[AES256_GCM,data:gOVx1hYodG7dKmlOkN4=,iv:afYcykkGj2drQym5lp5rQim5hHHOrlSzLwkEYWq5b88=,tag:yPLVfvC+jP/3g3oOlycN5w==,type:str]
    30.0.0.137: ENC[AES256_GCM,data:SFGmJlxBIHVJkfoXfUk=,iv:gbIKX6K7Ps/R0WjuoR4FHFxn7dk/RH4EU7JcvjcybTQ=,tag:hMmcE2UHR2a6VDeDSlrptQ==,type:str]
    30.0.0.54: ENC[AES256_GCM,data:RNazJIwi9HdPaEE6Klg=,iv:AZtCr3A+zJoggPBVf1btyH6YOKOeiyWDHhtzAKMQDyE=,tag:B17lgn0Nx/9fCJa70DNsKw==,type:str]
    30.0.0.107: ENC[AES256_GCM,data:I7jDyvn2fHTsZwkykS0=,iv:mPNblC1FY3DTKgKudrIqvOER8u0ubpFcgzV4coZuF6Y=,tag:+GD6XTCgZuo1Z0ju6ZE3JQ==,type:str]
    30.0.0.22: ENC[AES256_GCM,data:yhCdm/3aQjOuCb/SOaE=,iv:soy6V4mDbm84DWK13HIPj1iJKTms2d7ZL251I2tekXo=,tag:AFtmqDd9ZrrD8WiOF5QuBw==,type:str]
    30.0.0.67: ENC[AES256_GCM,data:2qHCiULndcuR1GT765U=,iv:LJKFn0DtN4SXoBRMLcOmu+jOdPCwHEj07bds0YUzpf0=,tag:MAplHXUO/CD+0WV7LxdJRA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mxysf0rqxnaehr4lswk9xp6th2njf4gxhs03ldszujuzc7d3fe4qaunngm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3ZGRpVFRZeWMvMnF5UDdq
            L2JCTTRSelMwVFpJemp4UXJzTUNDN1lad2hvClE3MHVIeFJqUFc2K3hLZE9mVk11
            TnNjelhMbDFYTnBVd1FOK1NBRjJ3NlUKLS0tIDFIeHRIam9JcGlXV0NocXRtZ0ZU
            RHVRTWtPL3BNTzI1L0s3QkZHYndtU00KdJMP088GLGVY1yslsooZuzrf4R8JxD4/
            YsnYyGU/kzHTu48erFVqiOzkMGJhGXgINoOtjb0ZpdmnOt9s4Y3Xtg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1manadmy373wugz43zmj73u973u24kyvkulgqnkzz4cmg22k0vv8quyvwfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZdDQzRU00NHBBRi9BZDRT
            SWRYTlRTK3AxS0w4cFdYZ3Zpamh4aVphNFZFCmhqcjJzaDR6dUM2dU5mQkpxUlZ6
            V1dNR1FWOTFKL0NCRkpMb2gwQzFIdlUKLS0tIFFUQVowMHFNdkg0MXFXK0NMNlZw
            NkFDenV5K0RtN3V1NkthL2FIM3VVT2MKURS9ADD1lcUbbxvEyVXtFtgVAwpPjLAT
            6MC9RJ/i9ir0RN0Z6OSorAhz/cQhh2E4AzWMTWFG72BJCBHdtu8g/g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14x4ps2cnajysxk94s7vqkj27nk9paukrkufku7qy3peskha7r43spppklt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByQ1BEd1lvVGNBQkl2K0pH
            L0hoUEQ1OTRKbHJGRW1vOWVMc0V0TnlOT3lFCmVUeWZYTk9uSGlNbjVQK010bHlK
            QTR3TGtOdXE4WndNWDNrd2VqOHkxOXMKLS0tIG5KcUVNWVI0dC8rOGZEMExSdmlq
            TytPdFBOcDE1ekVQRHhFMXpEbWY5a2cK2oPBUprnUdH1D7/0kuDoWr36PQqlmKPm
            f4/5qCk8QzP5/FPLhTPqXcxySOL++0DC+StNvUAq93nd5dO57boOzA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1hl2qdpez5zl47eqr0w3q2dep7j0t79s7m8kl34deg5ht96w8hsys2nmwne
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1MjRXMlhnbUlZdnJiZ2Ur
            MCtMTVdqZ1VaNy83YmFKWUN4SHRmT0tmaFNvCm5xVktudGlLaXNnYkt5SWxjcHBr
            N1RRMUVacWZBcXJtUy9mWi9wOTdkNEkKLS0tIEdKT2pURlFXRVYyaVJTUTFyZ2Vq
            cHRkeFJuQy9wbUtENzExbUM5ZmtNbjAKVRrJQEYO1RLaoZNUy2q7E5T1dFstaaAf
            x0GeJIOrhhJMEu6lYBj4BIZP7W+p4Vi362ez08Z4hf6cA7IS8bYgzg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age16cmlxsvzsleydkafhksyk3s36d0yf2rld7xpl8u2xz0xycadwfpq8c4cjt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLVzFvWDEvcjlTNTFya0xW
            R2NDajUrbGgrVU9ZSmRxd1BnVVYybVQ3cUhvCjFSMnBCU0JxQzNFK1JHWjJMbEQ1
            dlJJcEh4L0dyR05HQnJNYUhDWE9CWDgKLS0tIE9YVXY0S0M2MEgrUDkvOVJoRHlv
            RGlRZUdwUzZMNkhKVGJ0MmFKUlE3SHMKtxp0HWuj178cmhYRTDUW/ZrUbld4rtTI
            hiDeDjVpoEGVCiXyeU70H4+n6a/FoBCKu+G3RDQfGgpNMIbnJNo/dQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-27T04:57:31Z"
    mac: ENC[AES256_GCM,data:YsN34YY/s5tDDlZu4UBUuJd62iEPQHbUyeWWirhrROdPjnmjyx2oDb/HxCRH1pxeK+sc4feRxWQa3JIRKXHyT6NrkXo21t7GWIRdfThQKaySajuFgie2lznjW4v+m1GJPrT2qXSFKpStC0xx5H72KktxqsndOrYgZR026qHEbUQ=,iv:y7JMeH2zYekgrdazeO11R8bMiUn9VdkSoIU+PlN1fYA=,tag:5hiYPUtwl9Cn91VAfq87gg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
