forticlient:
    name: null
    descriptions: null
    gateway: ENC[AES256_GCM,data:d9qDTOKk212J548=,iv:RZxRa/4k1upyjrPfn4eGOSwFprzVkFWpyBqUp5qiFTI=,tag:RhrgzDHUNqcnHdZv4Ad/SQ==,type:str]
    port: ENC[AES256_GCM,data:4tPoIro=,iv:ydDwmg9uVqnCkUkEbzQOSmBfrv/PvHFExGA2iVgLkoQ=,tag:EiHrTXjOGtuhI5AbnbbhEA==,type:int]
users:
    chuai1: ENC[AES256_GCM,data:JzA8z52Y7RZqUcM=,iv:VT5dV8zvqfpuDT1yth8AJ7XiqE3sIqeXxdtebf/+ZxQ=,tag:UfmLy5QM0TYtgeDMpIpEJw==,type:str]
    chuai2: ENC[AES256_GCM,data:R5nmittWeg1lYq0=,iv:jaStnaFasH4PAsvZYCchft2AzWRvzjKcmUe/G9Flfv4=,tag:RywpPF2g49FPmIWGQGzUSQ==,type:str]
    chuai3: ENC[AES256_GCM,data:8I0IY6cvEw4I2TGZ,iv:ghSLch1C4AQ8t98+KasUIClxYM0j7hco/k3HW1zxY4U=,tag:3AC6of06LN+9hs+uZSCM4w==,type:str]
    chuai4: ENC[AES256_GCM,data:8+bEFVTIRf0T76U=,iv:UeLU1A7BtihcLwfP/JWSRtITdd4ieGvRIdnlcOMv0ds=,tag:g1eNbPx2tRHU95lR6N7/yg==,type:str]
    chuai5: ENC[AES256_GCM,data:boXerxA+E3yxEFU=,iv:hT3qRAh1Fud7cxTCcGqUC+t5pm2MXJ1xvm91+8KaTDk=,tag:SSDBxDK7p0xJ1zyi0Bnbvw==,type:str]
    chuai6: ENC[AES256_GCM,data:nTJhCFrImo1xNaMm,iv:HKnKjCUVARIHDrZAoBxy1afHR58x4qDtI48nT8Od2Ck=,tag:ZvoAVNagNQjDQP9yTGynZg==,type:str]
    chuai7: ENC[AES256_GCM,data:/w/b2URYoKdJYZc=,iv:fbwuDkZsrydWS9/Y4hnokt3aWiKSRIN8x2JOgjELMGQ=,tag:M1R07sQetGDiGUp1ZZt7Mg==,type:str]
    chuai8: ENC[AES256_GCM,data:t7aupMM6GseGxQU=,iv:4kyxE9LYyMe8LGvP4FFeJP+80yulLgKgYrDJxKImRyc=,tag:EgQp4WW8bAFlXnWxnHFVhg==,type:str]
servers:
    30.0.0.112: ENC[AES256_GCM,data:J98CCsBakFw4V3x1WPQ=,iv:sjdA4JL1ENiaJMJznhXj2M+qktuTLaZtqyQrCOL8ULc=,tag:k3ukqJ0AxTLyj/Jr4m75ug==,type:str]
    30.0.0.37: ENC[AES256_GCM,data:CunINVnHtBLDFSeBzyc=,iv:/eAe4N86GIj5sgpX6N0+r2b10vYiLuU0VzUk2Zlt86I=,tag:OFTXq22fraJG4OP81+JqGg==,type:str]
    30.0.0.55: ENC[AES256_GCM,data:6HhSuutXfVdc77ByroM=,iv:QC8jkqsF2IWNIaLsTUQ9hHqLdCDURK3vYXy6P9FcCO8=,tag:FuWpeSHsXkPKsHTw28LOYA==,type:str]
    30.0.0.17: ENC[AES256_GCM,data:weK+mZl7pkLhLtzjoKc=,iv:3x/Nj/NmdVx0tSoFjzecKDx+q3RzXQBK24d8546G4+E=,tag:eiCf+OJK3I5ddq7cV2y3UQ==,type:str]
    30.0.0.194: ENC[AES256_GCM,data:WmvZhgCaK510YQ+MbHA=,iv:JTyXAi2htt09Wt0bzWa+/NZbUDwnaWnNLhuGl7UDv5g=,tag:SyA8qDUx9lUhUXwDdqJy0w==,type:str]
    30.0.0.137: ENC[AES256_GCM,data:wgJ3p7AXNuaUDxZN//Q=,iv:umIG0nOEd9sXORe5IRJ+RkZ8teL7bNLm7PUE139O/08=,tag:70qMMkNSo1qEn6oQ6WfeGQ==,type:str]
    30.0.0.54: ENC[AES256_GCM,data:UQpTtLmvIssPiU3fyoY=,iv:Rd7dHxvmIMkCgJR8LDwgIjzYbtIfq+qy6JOAp5/uL50=,tag:FxBJuBqxx8GjCvQJpm07EA==,type:str]
    30.0.0.107: ENC[AES256_GCM,data:EU8HgrbGHQ6Awzqs57g=,iv:eItRGajbKaVHr2N3RWs8SQRidOY5hpoyI5IGp+FUtHc=,tag:MpgSoigOU+gmLOhbOxCoWw==,type:str]
    30.0.0.22: ENC[AES256_GCM,data:CPcijbJYoeFV1TJiUnk=,iv:LcZsy7qgo+aG4W1G7HNfNC7pyCQ11lRjC31lkr+YEx8=,tag:Ee8IRirCxnM4T3RN3W5sXA==,type:str]
    30.0.0.67: ENC[AES256_GCM,data:GH1EUXN1w/h0wuunbLg=,iv:IupYz3FoGeOE67B9xUVgVkssA63cDZHuf7Zc6ZfzE3k=,tag:Xokb32n6GaIEGBRzZklY1w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16cmlxsvzsleydkafhksyk3s36d0yf2rld7xpl8u2xz0xycadwfpq8c4cjt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCdi9TdjFnZEdMWG5aR3pO
            aGUxd3A5dElUMGE3c3ZOMzJVUnlycDV5ZjBnCjhGejhtOVJzYTZoVmRzeXBESzNr
            YktQTVJ3TjN6cWJXWEszZHUveXNyemMKLS0tIGtFbFAzbzg5cElFM3kzSk9VT2Rx
            T29IUnVCTElNeXllcTlGTm5yL0NwRUkKA3yaZfmczzmDxk4N2rNSJ1jo+1QwXO9Y
            dGRKeV/ua39p3deUecYsWqAYxZjIcZcEpoIRlQCs70wyjNNXKnchgQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1mxysf0rqxnaehr4lswk9xp6th2njf4gxhs03ldszujuzc7d3fe4qaunngm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJQTBoMmNtekQyaWd4WXBT
            OC83bHFISVlwaXYvZTFwSXkvK1JGK3JvbjJnCjZsa2JHMG82bXhxR1Fad2loZHp4
            cXVhQXBIdHhuYXdvMUI1Z0NGSVY5RGcKLS0tIGIxckNOQ1VYMW1Jdy9vR0NHT1Bs
            MlRKYWNjcERPT09kMERoZjVwZHJUQTAKzYlYNPuHwpd+mza4Sil/2kZs4+mEPJdO
            y7uUbrmxHn+TJC4eAx1ioPWhU7VAikwFPl5r72QFIx864+pLfj6Yfg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1manadmy373wugz43zmj73u973u24kyvkulgqnkzz4cmg22k0vv8quyvwfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMajcwUHRMdVNrTCtOMy9B
            ODc0alZaMHpCVTcvbmI5bGJ2Mkx4N3lkQnlBCnR4NDg2emFad2JXcDlpcUd0SFA1
            Sy81alA4SlRETmp6Z3kyV1FkRmYxWE0KLS0tIERJUWo1UnFLQTllVllXRXlvTDFT
            amFPR2R0MjRkaEZlWjd5VnluZzI5YmsKJx+OeoSM7NtwOEIX6kiBJnNC25xWhlTd
            uU81k5W/jd+pOKE32yZLNP47hkF8kgn9JrXEGHjvPibLZhvEjrQvHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-11T05:43:25Z"
    mac: ENC[AES256_GCM,data:SmldwlhiN5B5q/VykdPbsIx+csI/4LXb7uJrYP2mejBqUO5k5JO8k/pJblM/9yeYP0IhA3cm+i4QJe4i+eAJY9Z9RC5kIpcos0sDSeJY6wmu4FOyEagVsFzov2xuLq0zQPhgZBXuLxf19HQbDJ3xAyKnWb/+DhupaB+DVx3MaY4=,iv:qwrijzSap/ibhMOKx3lD4IUioyIPqj15lcqnVJUB3tA=,tag:xZzU3riZO6MuUstpgcRbWA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
